Update strava.yml

diff --git a/.github/workflows/strava.yml b/.github/workflows/strava.yml
--- a/.github/workflows/strava.yml
+++ b/.github/workflows/strava.yml
@@ -30,23 +30,23 @@ jobs:
       - name: Authenticate with Strava
         id: auth
         run: |
-          AUTHORIZATION=$(echo -ne "$STRAVA_CLIENT_ID:$STRAVA_CLIENT_SECRET" | base64)
-          RESPONSE=$(curl -sS -o /dev/null -w '%{http_code}' \
-          -X POST -H "Authorization: Basic $AUTHORIZATION" \
-          -H "Content-Type: application/json" \
-          -d "{ \"client_id\": \"$STRAVA_CLIENT_ID\", \"client_secret\": \"$STRAVA_CLIENT_SECRET\", \"refresh_token\": \"$STRAVA_REFRESH_TOKEN\", \"grant_type\": \"refresh_token\" }" \
-          https://www.strava.com/api/v3/oauth/token)
+          AUTHORIZATION="$(echo -ne "${STRAVA_CLIENT_ID}:${STRAVA_CLIENT_SECRET}" | base64)"
+          RESPONSE="$(curl -sS -o /dev/null -w '%{http_code}' \
+              -X POST -H "Authorization: Basic ${AUTHORIZATION}" \
+              -H "Content-Type: application/json" \
+              -d '{"client_id": "'"${STRAVA_CLIENT_ID}"'", "client_secret": "'"${STRAVA_CLIENT_SECRET}"'", "refresh_token": "'"${STRAVA_REFRESH_TOKEN}"'", "grant_type": "refresh_token" }' \
+              https://www.strava.com/api/v3/oauth/token)"
           
-          http_status="${response%%$'\n'*}
-          if (( http_status != 200 )) ; then
-          echo "::error ::Failed to authenticate with Strava API (HTTP status code: ${http_status})\ "*"
-          exit 1
+          http_status=${RESPONSE%%$'\n'}
+          if (( http_status != 200 )); then
+              echo "::error ::Failed to authenticate with Strava API (HTTP status code: ${http_status})"
+              exit 1
           fi
           
-          STRAVA_ACCESS_TOKEN="(${response#"access_token":"}| cut -d',' -f1)\ ""
-          STRAVA_ACCESS_TOKEN="{STRAVA_ACCESS_TOKEN##" : "}"
+          STRAVA_ACCESS_TOKEN=$({ response#"access_token":}"| cut -d',' -f1 )
+          STRAVA_ACCESS_TOKEN="${STRAVA_ACCESS_TOKEN%:*}}"
           
-          echo "::set-output name=authorization::*{STRAVA_ACCESS_TOKEN}*"
+          echo "::set-output name=authorization::$STRAVA_ACCESS_TOKEN"
       - name: Fetch Latest Activity
         id: fetch
         run: |
